### ISSUE TITLE
error: variable has incomplete type 'EVP_MD_CTX'

### ISSUE THREAD

**Issue by haxpor** [mongodb/mongo-php-driver#245]
I got the following error while doing `make all`.

    /Users/haxpor/mongo-php-driver/mongo-php-driver/src/libmongoc/src/mongoc/mongoc-scram.c:313:15: error: variable has incomplete type 'EVP_MD_CTX' (aka 'struct evp_md_ctx_st')
       EVP_MD_CTX digest_ctx;

I'm trying to build on Mac OSX 10.11.4

**Comment by derickr** [comment]
Which version of OpenSSL are you compiling against? And can you show more of the ``make all`` stage - in case there is another clue hidden away in its output?

**Comment by haxpor** [comment]
@derickr Thank you for your reply. I can't remember the version of openssl I compiled with. But I changed the approach to `sudo pecl install mongo`. But first I need to install `pecl'. It works now. I think I close this issue.

**Comment by jmikola** [comment]
@haxpor: FYI, `sudo pecl install mongo` will install the legacy driver. If you'd like the new driver (i.e. this repository), you'll want to install the `mongodb` package.
