### PR TITLE
PHPC-539: Include read concern in Query debug output

### PR DESCRIPTION
**Pull request by jmikola**
https://jira.mongodb.org/browse/PHPC-539

### CODE REVIEW

File: src/MongoDB/Query.c [hunk 1]
```diff
@@ -228,6 +228,23 @@ HashTable *php_phongo_query_get_debug_info(zval *object, int *is_temp TSRMLS_DC)
...
 	ADD_ASSOC_LONG_EX(&retval, "batch_size", intern->batch_size);
 
+	if (intern->read_concern) {
+#if PHP_VERSION_ID >= 70000
+		zval zv;
+#else
+		zval *zv;
+#endif
+
+		php_phongo_read_concern_to_zval(&zv, intern->read_concern);
```
Comment (derickr) [inline src/MongoDB/Query.c]: This doesn't work in PHP 5.4-5.6 as Travis says:

```
/home/travis/build/mongodb/mongo-php-driver/src/MongoDB/Query.c: In function ‘php_phongo_query_get_debug_info’:

/home/travis/build/mongodb/mongo-php-driver/src/MongoDB/Query.c:238:3: error: passing argument 1 of ‘php_phongo_read_concern_to_zval’ from incompatible pointer type [-Werror]

./php_phongo.h:133:6: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
```

File: src/MongoDB/Query.c [hunk 2]
```diff
@@ -228,6 +228,23 @@ HashTable *php_phongo_query_get_debug_info(zval *object, int *is_temp TSRMLS_DC)
 	ADD_ASSOC_LONG_EX(&retval, "limit", intern->limit);
 	ADD_ASSOC_LONG_EX(&retval, "batch_size", intern->batch_size);
 
+	if (intern->read_concern) {
+#if PHP_VERSION_ID >= 70000
+		zval read_concern;
+
+		php_phongo_read_concern_to_zval(&read_concern, intern->read_concern);
+		ADD_ASSOC_ZVAL_EX(&retval, "readConcern", &read_concern);
```
Comment (derickr) [inline src/MongoDB/Query.c]: Does ADD_ASSOC_ZVAL_EX copy the read_concern zval? If not, it's value is going to be out of scope when the function ends. I would at least run the tests covering this with valgrind.

Comment (jmikola) [inline src/MongoDB/Query.c]: Valgrind reported no issues. I poked into PHP 7's code for `add_assoc_zval_ex()` and it does appear to copy the zval argument. See: http://lxr.php.net/xref/PHP_7_0/Zend/zend_hash.c#552 and references to the `pData` argument therein. It's used with `ZVAL_COPY_VALUE()` when assigning the index.
